apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: query-param-app
  namespace: app
spec:
  podSelector:
    matchLabels:
      app: query-param-app
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9090
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
