apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: query-param-app
  namespace: app
spec:
  podSelector:
    matchLabels:
      app: query-param-app
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # ingress-nginx → port 8080 (HTTP trafik)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
    # Prometheus → port 9090 (metrics scrape)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9090
  egress:
    # DNS çözümleme
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
