apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-express-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: nodejs-express
    app.kubernetes.io/part-of: platform
    environment: prod
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=europe-west1-docker.pkg.dev/PROJECT_ID/nodejs-express-prod/app
    argocd-image-updater.argoproj.io/app.update-strategy: digest
    argocd-image-updater.argoproj.io/app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/app.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/hknisci/k8s-creating_cluster_with_ansible
    targetRevision: HEAD
    path: apps/nodejs-express/helm
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
      parameters:
        - name: image.repository
          value: europe-west1-docker.pkg.dev/PROJECT_ID/nodejs-express-prod/app
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-nodejs-express
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
