apiVersion: v1
kind: Namespace
metadata:
  name: staging-nodejs-express
  labels:
    environment: staging
    managed-by: argocd
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
