[master]
master  ansible_host=192.168.252.2  ansible_user=ubuntu  ansible_ssh_private_key_file=~/.ssh/id_ed25519

[workers]
worker1 ansible_host=192.168.252.3  ansible_user=ubuntu  ansible_ssh_private_key_file=~/.ssh/id_ed25519
worker2 ansible_host=192.168.252.4  ansible_user=ubuntu  ansible_ssh_private_key_file=~/.ssh/id_ed25519

[all:vars]
ansible_python_interpreter=/usr/bin/python3
