kubernetes_version: "1.32.0"
pod_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/12"
cluster_name: "dreamgames-cluster"
api_server_address: "192.168.56.10"
calico_version: "v3.29.1"
containerd_version: "1.7.23"
