{{- if .Values.keda.enabled -}}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "nodejs-express.fullname" . }}-keda-auth
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nodejs-express.labels" . | nindent 4 }}
spec:
  podIdentity:
    provider: gcp
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "nodejs-express.fullname" . }}-scaledobject
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nodejs-express.labels" . | nindent 4 }}
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nodejs-express.fullname" . }}
  pollingInterval: {{ .Values.keda.pubsub.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.pubsub.cooldownPeriod }}
  minReplicaCount: {{ .Values.keda.pubsub.minReplicas }}
  maxReplicaCount: {{ .Values.keda.pubsub.maxReplicas }}
  triggers:
    - type: gcp-pubsub
      authenticationRef:
        name: {{ include "nodejs-express.fullname" . }}-keda-auth
      metadata:
        subscriptionName: {{ .Values.keda.pubsub.subscriptionName | quote }}
        value: {{ .Values.keda.pubsub.threshold | quote }}
        projectId: {{ .Values.keda.pubsub.projectId | quote }}
        credentialsFromEnv: "GOOGLE_APPLICATION_CREDENTIALS"
{{- end }}
