{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nodejs-express.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nodejs-express.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "nodejs-express.selectorLabels" . | nindent 6 }}
{{- end }}
