apiVersion: v1
kind: Namespace
metadata:
  name: prod-nodejs-express
  labels:
    environment: prod
    managed-by: argocd
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
