apiVersion: v1
kind: Namespace
metadata:
  name: dev-nodejs-express
  labels:
    environment: dev
    managed-by: argocd
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
